// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'annotations-column-name'
  | 'pref-annotationscount-hide-zeros'
  | 'pref-annotationscount-show-icon'
  | 'pref-subtitle'
  | 'pref-title';
